config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :api do
    resources :characters do
      resources :relationships, only: %i[create destroy]

      get 'appearance'
      get 'traits'
      get 'relationships'
    end
  end

  root 'characters#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

# Documentation:
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/character.rb
# frozen_string_literal: true

class Character < ApplicationRecord
  has_many :relation_tos, class_name: 'Relationship', foreign_key: :character_from_id, inverse_of: :character_from,
                          dependent: :destroy
  has_many :character_tos, through: :relation_tos, source: :character_to

  # Inverse character relationships
  has_many :relation_froms, class_name: 'Relationship', foreign_key: :character_to_id, inverse_of: :character_to,
                            dependent: :destroy
  has_many :character_froms, through: :relation_froms, source: :character_from

  # TODO: Add location_of_birth and events involved
  def to_formatted_json
    response_body =
      {
        id: id,
        name: name_data,
        age: age,
        height: height,
        weight: weight,
        appearance: appearance&.force_encoding('utf-8'),
        description: description&.force_encoding('utf-8'),
        relationships: character_tos.pluck(:id),
        date_of_birth: date_of_birth
      }

    # Merge timestamps
    response_body.merge!(timestamps)

    response_body.to_json
  end

  private

  def name_data
    {
      first: first_name,
      last: last_name,
      full: "#{first_name} #{last_name}"
    }
  end

  def timestamps
    {
      created_at: created_at.to_formatted_s(:iso8601),
      updated_at: updated_at.to_formatted_s(:iso8601)
    }
  end
end

app/models/relationship.rb
# frozen_string_literal: true

class Relationship < ApplicationRecord
  belongs_to :character_from, foreign_key: :character_from_id, class_name: 'Character', inverse_of: :relation_tos
  belongs_to :character_to, foreign_key: :character_to_id, class_name: 'Character', inverse_of: :relation_froms
end

app/controllers/api/characters_controller.rb
# frozen_string_literal: true

# Documentation:
# CharacterController corresponds to the respective API
module Api
  class CharactersController < ApiController
    # GET api/characters
    def index
      # Health check
      render json: { status: 'OK' }, status: 200
    end

    # POST api/characters
    def create
      new_character = Character.create(character_params)
      render json: { character_id: new_character.id }, status: 200
    end

    # GET api/characters/:id
    def show
      render json: { status: 'Character does not exist' }, status: 404 and return if character.nil?

      render json: character.to_formatted_json, status: 200
    end

    # TODO: implement put/patch request flow
    def update; end

    def destroy
      render json: { status: 'Failed to delete character' }, status: 404 and return if character.nil?

      character.destroy
      render json: { status: 'Successfully deleted character' }, status: 200
    end

    def appearance; end

    def traits
      render json: { status: 200 }
    end

    def relationships; end

    private

    def character
      Character.find_by_id(params[:id])
    end

    def character_params
      params.require(:character).permit(:id, :first_name, :last_name, :traits, :appearance, :age, :description, :height,
                                        :weight, :date_of_birth)
    end
  end
end

app/controllers/api/relationships_controller.rb
# frozen_string_literal: true

# Documentation:
module Api
  class RelationshipsController < ApiController
    def create
      new_relationship = Relationship.create(relationship_params)
      render json: { relationship_id: new_relationship.id }, status: 200
    end

    def destroy
      render json: { status: 'Failed to delete relationship' }, status: 404 and return if relationship.nil?

      relationship.destroy
      render json: { status: 'Successfully deleted relationship' }, status: 200
    end

    private

    def relationship
      Relationship.find_by_id(params[:id])
    end

    def relationship_params
      params.require(:relationship).permit(:id, :character_from_id, :character_to_id)
    end
  end
end

app/controllers/api_controller.rb
# frozen_string_literal: true

class ApiController < ActionController::API
  # Might be good to run authentication in a certain type of program (not necessary here though)

  # include ::ActionController::Caching
  # self.cache_store = :mem_cache_store
end

app/views/characters/_form.html.erb
<%= form_with(model: @character) do |f| %>
    <div class="field">
        <%# f.label :name %><br />
        <%# f.text_field :name %>
    </div>
    <div class="field">
        <%= f.label :traits %><br />
        <%= f.text_field :traits %>
    </div>
    <div class="field">
        <%= f.label :appearance %><br />
        <%= f.text_area :appearance %>
    </div>
    <div class="actions">
        <%= f.submit %>
    </div>
<% end %>

app/views/characters/edit.html.erb
<!-- <%= render partial: "_form.html.erb" %> -->

app/views/characters/index.html.erb
<h1> Sample view for characters </h1>

<%= link_to 'Create character', new_character_path %>

<ul>
    <% @characters.each do |c| %>
        <!-- <li><%# link_to c.traits, character_path(c) %></li> -->
        <li>
            <%= "#{c.first_name} #{c.last_name}" %> -
            <%= link_to "remove", character_path(c), method: :delete, data: { confirm: "Really?" } %>
        </li>
    <% end %>
</ul>

app/views/characters/new.html.erb
<%= render partial: "characters/form" %>

app/views/layouts/_application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
    <%#= javascript_include_tag :defaults %>

    <%# stylesheet_link_tag    'application', media: 'all' %>
    <%# javascript_include_tag 'application' %>
    <%# javascript_include_tag "rails-ujs" %>
  </head>
  <body>
    
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
    <%= javascript_include_tag :defaults %>

    <%# stylesheet_link_tag    'application', media: 'all' %>
    <%# javascript_include_tag 'application' %>
    <%# javascript_include_tag "rails-ujs" %>
  </head>
</html>